# Generated by Django 5.0.3 on 2024-03-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shirt_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='is_bestselller',
            field=models.BooleanField(default=False),
        ),
    ]
