# Generated by Django 5.0.3 on 2024-03-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bestselller',
            field=models.BooleanField(default=False),
        ),
    ]
