# Generated by Django 5.0.3 on 2024-03-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
