# Generated by Django 5.0.3 on 2024-03-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='brand',
        ),
    ]
