# Generated by Django 5.0.3 on 2024-03-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suggestion',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
