# Generated by Django 5.0.3 on 2024-03-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
